#
# COPYRIGHT Ericsson 2024
#
#
#
# The copyright to the computer program(s) herein is the property of
#
# Ericsson Inc. The programs may be used and/or copied only with written
#
# permission from Ericsson Inc. or in accordance with the terms and
#
# conditions stipulated in the agreement/contract under which the
#
# program(s) have been supplied.
#

site_name: OSS APP Onboarding Documentatation
site_description: OSS APP Onboarding Documentatation
docs_dir: marketplace

nav:
  - Application Developers Guide: developers_guide/developers_guide_template.md
  - User Guide: user_guide/user_guide_template.md

plugins:
  - techdocs-core

markdown_extensions:
  - pymdownx.snippets:
      check_paths: true
