#
# COPYRIGHT Ericsson 2022
#
#
#
# The copyright to the computer program(s) herein is the property of
#
# Ericsson Inc. The programs may be used and/or copied only with written
#
# permission from Ericsson Inc. or in accordance with the terms and
#
# conditions stipulated in the agreement/contract under which the
#
# program(s) have been supplied.
#

documents:
  - name: "eric-oss-app-onboarding-sdk-docs"
    filepath: build/doc-md/eric-oss-app-onboarding-sdk-docs.zip
    default: true
  - name: "eric-oss-app-onboarding-openapi"
    filepath: build/doc-md/eric-oss-app-onboarding-openapi.zip