#
# COPYRIGHT Ericsson 2021
#
#
#
# The copyright to the computer program(s) herein is the property of
#
# Ericsson Inc. The programs may be used and/or copied only with written
#
# permission from Ericsson Inc. or in accordance with the terms and
#
# conditions stipulated in the agreement/contract under which the
#
# program(s) have been supplied.
#

kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ template "eric-oss-app-onboarding.name" . }}-psp-binding
  labels:
{{- include "eric-oss-app-onboarding.labels" . | nindent 4 }}
  annotations:
{{- include "eric-oss-app-onboarding.annotations" . | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: {{ include "eric-oss-app-onboarding.fullname" . }}
roleRef:
  kind: ClusterRole
  name: {{ template "eric-oss-app-onboarding.privileged.cluster.role.name" . }}
  apiGroup: rbac.authorization.k8s.io
