#
# COPYRIGHT Ericsson 2021
#
#
#
# The copyright to the computer program(s) herein is the property of
#
# Ericsson Inc. The programs may be used and/or copied only with written
#
# permission from Ericsson Inc. or in accordance with the terms and
#
# conditions stipulated in the agreement/contract under which the
#
# program(s) have been supplied.
#

apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "eric-oss-app-onboarding.name" . }}-sa
  labels:
{{- include "eric-oss-app-onboarding.labels" . | nindent 4 }}
  annotations:
{{- include "eric-oss-app-onboarding.annotations" . | nindent 4 }}
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ template "eric-oss-app-onboarding.name" . }}-role
  labels:
{{- include "eric-oss-app-onboarding.labels" . | nindent 4 }}
  annotations:
{{- include "eric-oss-app-onboarding.annotations" . | nindent 4 }}
rules:
  - apiGroups:
      - ""
      - "apps"
      - "batch"
    resources:
      - pods
      - jobs
      - jobs/status
    verbs:
      - get
      - list
      - watch
      - create
      - delete
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ template "eric-oss-app-onboarding.name" . }}-role-binding
  labels:
{{- include "eric-oss-app-onboarding.labels" . | nindent 4 }}
  annotations:
{{- include "eric-oss-app-onboarding.annotations" . | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: {{ template "eric-oss-app-onboarding.name" . }}-sa
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ template "eric-oss-app-onboarding.name" . }}-role