#
# COPYRIGHT Ericsson 2023
#
#
#
# The copyright to the computer program(s) herein is the property of
#
# Ericsson Inc. The programs may be used and/or copied only with written
#
# permission from Ericsson Inc. or in accordance with the terms and
#
# conditions stipulated in the agreement/contract under which the
#
# program(s) have been supplied.
#

{{- $serviceMesh := include "eric-oss-app-onboarding.service-mesh-enabled" . | trim -}}
{{- $tls := include "eric-oss-app-onboarding.global-security-tls-enabled" . | trim -}}
{{- if and (eq $serviceMesh "true") (eq $tls "true") -}}
  {{- include "eric-oss-app-onboarding-eric-data-object-storage-mn-secret" . }}
{{- end }}